version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  producer:
    build:
      context: ./producer
    depends_on:
      - kafka
    volumes:
      - shared_data:/shared
    environment:
      KAFKA_BROKER: kafka:9092
      SHARED_DIR: /shared

  stream_processor:
    build:
      context: ./stream_processor
    depends_on:
      - kafka
      - postgres
    volumes:
      - shared_data:/shared
    environment:
      KAFKA_BROKER: kafka:9092
      POSTGRES_HOST: postgres
      POSTGRES_DB: hospital_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  batch_processor:
    build:
      context: ./batch_processor
    depends_on:
      - postgres
    volumes:
      - shared_data:/shared
    environment:
      SHARED_DIR: /shared
      POSTGRES_HOST: postgres
      POSTGRES_DB: hospital_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  scheduler:
    build:
      context: ./scheduler
    depends_on:
      - producer
      - batch_processor
      - stream_processor
    volumes:
      - shared_data:/shared

volumes:
  postgres_data:
  shared_data:
